# Generated by Django 4.2.1 on 2023-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'normal'), ('OFFICIAL', 'official')], default='NORMAL', max_length=140),
        ),
    ]
